apiVersion: v1
kind: Service
metadata:
  name: devops-redis-service 
spec:
  selector:
    app: devops-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-redis-deployment
  labels:
    app: devops-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-redis
  template:
    metadata:
      labels:
        app: devops-redis
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"