version: '3.8'
services:
  api:
    container_name: devops-node-api
    image: pfalck/devopstest:dev
    ports:
      - "${APP_PORT}:${APP_PORT}" 
    env_file:
      - .env
    environment:
      NODE_ENV: developer
    depends_on:
      - redis
    restart: always

  # NUEVO SERVICIO: Redis
  redis:
    image: redis:6-alpine
    container_name: devops-redis
    ports:
      - "6379:6379"
    restart: always