#este es el cambio 

apiVersion: v1
kind: Service
metadata:
  name: devops-app-service-dev
  namespace: dev
  labels:
    app: devops-app
    env: dev
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: devops-app
    env: dev