# kubernetes/dev/02_secret_dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: devops-app-secret-dev # CORREGIDO: Nombre ÚNICO
  namespace: dev
type: Opaque
stringData:
  # ATENCIÓN: Usar claves de desarrollo
  DEV_OPS_API_KEY: 2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
  JWT_TRANSACTION_SECRET: Pfalconi_1529